### ISSUE TITLE
WSL not showing text

### ISSUE THREAD

**Issue by elsaco** [lhecker/rainbowbench#5]
Running `rainbowbench` inside WSL is not showing any chars or they are the same color as the background since `ctrl + c` does copy text.

Sample run:
![rainbowbench_wsl](https://user-images.githubusercontent.com/3933920/169096260-82167642-ed3a-4b7a-b28f-71cb0e63ecb8.png)

**Comment by lhecker** [comment]
I changed the color algorithm at some point to generate foreground/text colors that are extremely close to the background color. This then creates "smooth" rainbows which I found to be more visually pleasing.

If you remove the `"\x1b[?1049h"` and `"\x1b[?1049l"` sequences from `main.cpp` you can press Ctrl-C and inspect the colored output closer. You should see the characters then. BTW You can run the application as `rainbowbench <number_of_colors>` to generate fewer colors which will make it more obvious. 🙂

**Comment by lhecker** [comment]
Here's a screenshot of `rainbowbench 20`:
![image](https://user-images.githubusercontent.com/2256941/169105557-c96d1581-b1f6-4bf8-aeec-5cdaa365d4ca.png)

**Comment by lhecker** [comment]
I'm going to go ahead and close this issue as answered. If you feel like I haven't answered it properly, or if you have any questions whatsoever, feel free to ask. 🙂
